# Generated by Django 3.1.4 on 2021-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='Joe_the_default_guy', max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
