# Generated by Django 3.1.4 on 2021-05-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210513_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='tweet',
        ),
    ]
